### ISSUE TITLE
sseramemes roadmap 2023

### ISSUE THREAD

**Issue by arantespp** [sibelius/ccsseraphini#1437]
- [ ] restructure codebase in modules—receive meme, transform meme, post meme, Twitter mentions.
- [ ] send errors to a Discord channel.
- [ ] post on Instagram.
- [ ] fix tweet mentions error that stops mentions after the first error.
- [ ] retweet mentions
- [ ] add Discord commands.
- [ ] create a landing page and use sseramemes.com.
