### ISSUE TITLE
sseramemes roadmap

### ISSUE THREAD

**Issue by arantespp** [sibelius/ccsseraphini#547]
# Feature Request

- [x] Add watermark to pictures automatically (https://github.com/sibelius/ccsseraphini/pull/553/).
- [x] Add a timeout to RT memes tweet after some period (https://github.com/sibelius/ccsseraphini/pull/551).
- [x] Listen to tweets that mention @/sseramemes. Send these tweets to the memes channel to vote if we'll retweet them (https://github.com/sibelius/ccsseraphini/issues/576)
- [x] Run code on EC2 or another infrastructure.
- [ ] Create a landing page on sseraphini.cc showing the latest memes and how the automation works.
- [ ] Create a feature to listen to "@sseramemes memefy" and send the tweet to be memefied URL to the meme channel.
- [ ] Add Sentry and send the messages to the meme channel.

## Why it is needed

Fully automate sseramemes :rocket:

**Comment by arantespp** [comment]
> Do we have the watermark? perhaps we could discuss using a tool like [jimp.js](https://yarnpkg.com/package/jimp)

Nice lib, I didn't know it. We're using [this image](https://twitter.com/MyNickIsNick_/status/1519026700306239488 as the logo. Do you know if jimp.js allows us to insert a 30x30 image at the right bottom of another image?

**Comment by Grubba27** [comment]
link to water mark docs [here](https://www.npmjs.com/package/jimp#:~:text=image.mask(%C2%A0src%2C%C2%A0x%2C%C2%A0y%C2%A0)%3B%C2%A0)
I think it would be something like this code below : 

const Jimp = require('jimp);

```js
Jimp.read(MEME_TO_BE_UPLOADED__URL)
  .then(image => {
    // Do stuff with the image.
    image.mask( WATER_MARK_URL , Jimp.HORIZONTAL_ALIGN_LEFT, Jimp.VERTICAL_ALIGN_BOTTOM );  
  })
  .catch(err => {
    // Handle an exception.
  });
```

Maybe some tests to get in the right spot like the x and y axis + some px but i dont think it should take much time

**Comment by jeffque** [comment]
Error handling should be a little more user friendly. For example, it could send a message with the error in the discord server

**Comment by sibelius** [comment]
good enough
